[tool.poetry]
name = "llm-tutorials"
version = "0.1.0"
description = ""
authors = ["Sajal Sharma <sajal2692@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
